#### Prerequisite Knowledge
- Bayes theorem

In [2]:
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny',
'Rainy','Sunny','Overcast','Overcast','Rainy']
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [ ]:
from sklearn import preprocessing

# Converting String Text to Int Label Encoding
le = preprocessing.LabelEncoder()
weather_encoded = le.fit_transform(weather)
weather_encoded

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [6]:
temp_encoded = le.fit_transform(temp)
label = le.fit_transform(play)

In [7]:
temp_encoded

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

In [8]:
label

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [11]:
features = list(zip(weather_encoded, temp_encoded))
print(features)

[(np.int64(2), np.int64(1)), (np.int64(2), np.int64(1)), (np.int64(0), np.int64(1)), (np.int64(1), np.int64(2)), (np.int64(1), np.int64(0)), (np.int64(1), np.int64(0)), (np.int64(0), np.int64(0)), (np.int64(2), np.int64(2)), (np.int64(2), np.int64(0)), (np.int64(1), np.int64(2)), (np.int64(2), np.int64(2)), (np.int64(0), np.int64(2)), (np.int64(0), np.int64(1)), (np.int64(1), np.int64(2))]


In [12]:
# Import Gaussian Naive Bayes
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(features, label)
predicted = model.predict([[0, 2]])
predicted

array([1])