## KNN

In [8]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [22]:
from sklearn.datasets import load_iris

iris = load_iris()


In [23]:
name = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
dataset = pd.DataFrame(data = iris.data, columns = iris.feature_names)
dataset['Class'] = iris.target

In [26]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [28]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [29]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

In [30]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.90      0.95        10
           2       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

